<a href="https://colab.research.google.com/github/Junjaee/Study/blob/main/MachineLearning_DeepLearning/Study/12_Tensorflow2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib as mpl
import seaborn as sns

import matplotlib.font_manager as fm
# font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
# plt.rc("font", family=font_name)

mpl.rcParams["axes.unicode_minus"] = False

import keras
from keras.models import Sequential, load_model
from keras.layers.core import Dense
from keras.optimizers import RMSprop, Adam, SGD
from keras.utils import np_utils
from keras.callbacks import EarlyStopping

In [4]:
print(tf.__version__)
print(tf.keras.__version__)

2.5.0
2.5.0


### 특징

- Keras와 즉시 실행(eager execution)을 이용한 쉬운 모델 작성
- 어떤 플랫폼에서든 튼튼한(robust) 모델을 배포
- 연구를 위한 강력한 실험법
- deprecated된 API를 정리하고 중족을 줄여서 API를 단순화

### API

- tf.data
- tf.keras

In [6]:
t1 = tf.constant(10)
print(t1)

t2 = t1 + 5
print(t2)

print(t2.numpy())

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
15


In [8]:
t1 = tf.constant([2., 4., 5.])
print(t1)
print(t1.numpy())

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)
[2. 4. 5.]


In [13]:
t1 = tf.constant("hello world")
print(t1)
print(t1.numpy())

t2 = tf.constant("안녕하세요")
print(t2)
print(t2.numpy().decode("utf-8"))

tf.Tensor(b'hello world', shape=(), dtype=string)
b'hello world'
tf.Tensor(b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94', shape=(), dtype=string)
안녕하세요


In [20]:
# placeholder도 지원X

a = tf.Variable(tf.cast(3, dtype=float))
b = tf.Variable(4.5)

print(a + b)
print(a.numpy() + b.numpy())

##############################################

a = tf.Variable(tf.zeros(shape=()))
b = tf.Variable(tf.zeros(shape=()))

@tf.function
def add(x):
    return (a + x[0]) + (b + x[1])

print(add([3, 4.5]))
print(add([[1, 3], [2, 4]]))

tf.Tensor(7.5, shape=(), dtype=float32)
7.5
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)


### 1. 선형 회귀 모델

In [ ]:
##### 데이터 준비
x_train = [1, 2, 3]
y_train = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
b = tf.Variable(tf.random_normal([1]), dtype=tf.float32)

##### 가설 준비(y = Wx)
hypot = W * x_train + b

##### 비용 함수
cost = tf.reduce_mean(tf.square(hypot - y_train))

##### 최저비용 학습을 위한 경사 하강 알고리즘(Gradient Descent)
gradient = tf.reduce_mean((hypot-y_train)*x_train)
learning_rate = 0.1
descent = W - (learning_rate * gradient)
update = W.assign(descent)

################## Graph 작업 완료

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(20):
    _, weight, c = sess.run([update, W, cost])
    print(step, weight, c)

sess.close()

In [23]:
x_train = [1, 2, 3]
y_train = [1, 2, 3]

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(1, input_dim=1))
sgd = tf.keras.optimizers.SGD(lr=0.01)
model.compile(loss="mse", optimizer=sgd)
model.fit(x_train, y_train, epochs=20)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/20
1/1 [==============================] - 1s 522ms/step - loss: 4.4058
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 3.4863
Epoch 3/20
1/1 [==============================] - 0s 4ms/step - loss: 2.7595
Epoch 4/20
1/1 [==============================] - 0s 4ms/step - loss: 2.1850
Epoch 5/20
1/1 [==============================] - 0s 4ms/step - loss: 1.7308
Epoch 6/20
1/1 [==============================] - 0s 5ms/step - loss: 1.3718
Epoch 7/20
1/1 [==============================] - 0s 6ms/step - loss: 1.0880
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.8637
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6863
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.5461
Epoch 11/20
1/1 [==============================] - 0s 5ms/step - loss: 0.4353
Epoch 12/20
1/1 [==============================] - 0s 7ms/step - loss: 0.3477
Epoch 13/20
1/1 [==============================] - 0s 5ms/step - loss: 

In [24]:
print(model.weights)
print(model.weights[0].numpy() * x_train[0] + model.weights[1].numpy())
print(model.weights[0].numpy() * x_train[1] + model.weights[1].numpy())
print(model.weights[0].numpy() * x_train[2] + model.weights[1].numpy())

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.77234364]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.30719692], dtype=float32)>]
[[1.0795405]]
[[1.8518841]]
[[2.6242278]]


### 2. 컬러 이미지 분류
- https://www.cs.toronto.edu/~kriz/cifar.html


In [27]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib as mpl
import seaborn as sns

import matplotlib.font_manager as fm
# font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
# plt.rc("font", family=font_name)

mpl.rcParams["axes.unicode_minus"] = False

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, BatchNormalization
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.datasets import cifar10

from six.moves import cPickle
from sklearn.metrics import classification_report, confusion_matrix